### ISSUE TITLE
Add 'disabled' as a prop to ReactRanger

### ISSUE THREAD

**Issue by mjcarlin** [tannerlinsley/react-ranger#7]
I would like to be able to set the enabled/disabled state of the widget as a whole.

**Comment by minecrawler** [comment]
How can this be done? I cannot find any docs and also there doesn't seem to be any commit for it https://github.com/TanStack/ranger/commits/main/?after=5bdf486292418cc6e71f72fa023ddb1295051f04+69

I can only think of passing all event handlers through some custom logic first, which checks for disabled state, which isn't nice.
